server.host: "0.0.0.0"
server.publicBaseUrl: "${SERVER_PUBLICBASEURL}"
elasticsearch.hosts: ["${ELASTICSEARCH_HOSTS}"]
elasticsearch.username: "${ELASTICSEARCH_USERNAME}"
elasticsearch.password: "${ELASTICSEARCH_PASSWORD}"
i18n.locale: "ko-KR"
